default:
  image: python:3.7

include:
  - project: dke/apps/templates/job-templates
    file: job-templates.yml
  - project: nse/ci
    file:
      - /ci/lib/common.yml
      - /ci/jobs/build-package.yml
      - /ci/jobs/publish-package.yml

stages:
  - unit-test
  - build
  - publish

build-package:
  rules:
    - when: on_success
publish-package:
  rules:
    - if: $CI_COMMIT_TAG

unit_test:
  stage: unit-test
  extends: .unit-tests
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
  before_script:
    - pip install -r requirements.txt
    - pip install .
  variables:
    SRC_PROJECT: '$CI_PROJECT_PATH'
    TEST_FOLDER: 'tests'
    KUBERNETES_MEMORY_LIMIT: 8Gi
    KUBERNETES_MEMORY_REQUEST: 8Gi
  artifacts:
    paths:
      - $TEST_FOLDER/data/*
